nelmio_api_doc:
    documentation:
        info:
            title: "Bot Chat Log API"
            description: "API для работы с логами чатов"
            version: "1.0.0"
    areas:
        path_patterns:
            - ^/api